### ISSUE TITLE
Incorrect error messages when not passing network to instance

### ISSUE THREAD

**Issue by pasmon** [pulumi/pulumi-oci#11]
### What happened?

Trying to create an instance to OCI with Pulumi, but I find the documentation lacking as I understand examples better than API documents.

I understand that OCI should create a network automatically when creating instances (that is what happens when creating instances in OCI console), but that doesn't seem to happen with this provider.

Is there something missing from the code?

### Steps to reproduce

Do the "Pulumi Configuration" from here:
https://www.pulumi.com/registry/packages/oci/installation-configuration/

Create a Pulumi program:
```python
import pulumi_oci as oci
vm1 = oci.core.Instance("oci-instance1",
                availability_domain="Dtqv:EU-STOCKHOLM-1-AD-1",
                compartment_id="ocid1.tenancy.oc1..<redacted>",
                shape="VM.Standard.A1.Flex",
                source_details=oci.core.InstanceSourceDetailsArgs(
                    source_id="ocid1.image.oc1.eu-stockholm-1.aaaaaaaaicyhmukvotwdsfxgwk73p2z3kk344bxbg2ycwltyyktw26hz3kna",
                    source_type="image",
                ),
                shape_config=oci.core.InstanceShapeConfigArgs(
                    memory_in_gbs=12,
                    ocpus=2,
                ),
                metadata={"ssh_authorized_keys": "ssh-ed25519 == <redacted>"}
)
```
Run the Pulumi program.

### Expected Behavior

Expected the instance to be created.

### Actual Behavior

```
Diagnostics:
  oci:Core:Instance (oci-instance1):
    error: 1 error occurred:
        * 400-InvalidParameter, Invalid Subnet: null
    Suggestion: Please update the parameter(s) in the Terraform config as per error message Invalid Subnet: null
    Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance
    Request Target: POST https://iaas.eu-stockholm-1.oraclecloud.com/20160918/instances
    Provider version: 4.72.0, released on 2022-04-21. This provider is 5 Update(s) behind to current.
    Service: Core Instance
    Operation Name: LaunchInstance
    OPC request ID: <redacted>
```

### Versions used

```
CLI          
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME    VERSION
oci     0.1.1
python  unknown
rke     3.2.0

Host     
OS       arch
Version  
Arch     x86_64

This project is written in python (/home/username/.local/share/virtualenvs/provision-oci-W0i-7q1y/bin/python3 v3.10.4)

Current Stack: dev

TYPE                       URN
pulumi:pulumi:Stack        urn:pulumi:dev::oci-rke-provision::pulumi:pulumi:Stack::oci-rke-provision-dev
pulumi:providers:oci       urn:pulumi:dev::oci-rke-provision::pulumi:providers:oci::default_0_1_1
pulumi:providers:rke       urn:pulumi:dev::oci-rke-provision::pulumi:providers:rke::default_3_1_1
rke:index/cluster:Cluster  urn:pulumi:dev::oci-rke-provision::rke:index/cluster:Cluster::masterofclusters

NAME            VERSION
cryptography    36.0.1
flake8          4.0.1
Jinja2          3.0.3
logilab-common  1.8.3
packaging       21.3
pip             21.3.1
pulumi-oci      0.1.1
pulumi-rke      3.2.0
pylint          2.12.2
resolvelib      0.5.4
wheel           0.37.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @pasmon 

My apologies our documentation is not better here. Unfortunately, as we use the underlying terraform provider / sdk, no automatic creation of a network happens here - IaC is declarative so that would not track that specific resource in state

You will need to create a network and attach it to the Instance as part of your pulumi update.

what is not acceptable is that error message - we will ensure that doesn't happen.

I am going to keep that issue open to track that work to fix these error messages to make them better

Paul

**Comment by pasmon** [comment]
Hi and thanks Paul for the update! Certainly the documentation improvement is in order and I'm happy with that.

I'm going to try to create the network myself then.

**Comment by guineveresaenger** [comment]
I am going to close this out as stale, and there's a good chance this has been fixed in a more recent version.

See [current `oci.Core.Instance` documentation](https://www.pulumi.com/registry/packages/oci/api-docs/core/instance/).

Please, reopen the issue if you're still having trouble. Thanks!
