### ISSUE TITLE
Not able to remove resources

### ISSUE THREAD

**Issue by chanstev** [pulumi/pulumi-oci#22]
### What happened?

Using python, even the command "pulumi down" come back with resource delete successfully, the OCI resources remain in OCI without removal at all. 

<img width="901" alt="image" src="https://user-images.githubusercontent.com/22254955/172402971-211f2922-a2aa-4f02-bd4a-6c65db3372de.png">

### Steps to reproduce

- Python 3.9.6
- pulumi_oci==0.1.1
- pulumi == 3.33.2

-- Create resources with "pulumi up" with simple python like below
import pulumi
import pulumi_oci as oci
oci.identity.Compartment("Test",compartment_id="ocid1.compartment.oc1.xxxxxxxxxxxxxxxxx",description="This is a test")

-- Destroy resources with "pulumi down"
 

### Expected Behavior

Provisioned resources in OCI be removed after pulumi down report success

### Actual Behavior

Provisioned resources in OCI still available (even after days, so it's not a time lag problem) after pulumi down reported success.

### Versions used

NAME        VERSION
pip         22.1
pulumi-oci  0.1.1
setuptools  62.2.0
wheel       0.37.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @chanstev 

Apologies that this isn't clear in our docs but you need to set enableDelete in your resource

https://www.pulumi.com/registry/packages/oci/api-docs/identity/compartment/

Paul

enableDelete
Defaults to false. If omitted or set to false the provider will implicitly import the compartment if there is a name collision, and will not actually delete the compartment on destroy or removal of the resource declaration. If set to true, the provider will throw an error on a name collision with another compartment, and will attempt to delete the compartment on destroy or removal of the resource declaration.

**Comment by stack72** [comment]
Hi @chanstev 

did this work for you?

Paul

**Comment by chanstev** [comment]
Hi Paul, @stack72 it works. Thanks for the guidance.

**Comment by stack72** [comment]
ah great news :)
