### ISSUE TITLE
Rename to pulumi-oracle-cloud

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi-oci#23]
I’m worried that reserving the oci name for Oracle Cloud means we’d need a really random name for a provider that builds OCI artifacts. 

https://github.com/opencontainers/artifacts

Container images are now OCI images and within the Cloud Native space, we’re seeing a lot of new patterns emerging that are built on top of OCI too. 

I know Terraform call this OCI, but this is a really random name from Oracle - especially as members of the Open Container Initiative.

**Comment by jkisk** [comment]
@stack72 do you have thoughts here?

**Comment by stack72** [comment]
OCI is oracle cloud infrastructure. We agreed this name with them when we talked with them about building it.

We'd need to go back to them on this if we wanted to change it - I don't believe it's just up to us here as it's now been marketed on their side as OCI.

I can ask internally here to see but I can't promise we will change this

**Comment by EladGabay** [comment]
I think we should keep it, it's OCI like it's AWS and not "Amazon Cloud".

**Comment by stack72** [comment]
Going to close this out as this I'm not sure we can change this at this time

**Comment by rawkode** [comment]
> I think we should keep it, it's OCI like it's AWS and not "Amazon Cloud".

Oracle Cloud is a member of the Open Container Initiative. It’s not quite the same.
