### ISSUE TITLE
Bridge update PRs do not auto merge because of changelog check

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-oci#266]
### What happened?

Looks like automatic bridge update PRs get stuck because they're expected to edit CHANGELOG as one of the PR checks. I've tried removing this rule by editing the repo settings directly. Curious if we're maintaining it through automation somewhere and I'd need to propagate the edit there. An alternative fix is to add "no changelog required" labels to the automatic bridge updates.

### Example

Most recent PR requiring intervention: https://github.com/pulumi/pulumi-oci/pull/265

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
I think @iwahbe has looked into removing this check from pretty much everywhere. Or am I misremembering?

**Comment by t0yv0** [comment]
Appreciate if you can find a ticket for that to cross-check. As recently as a few days ago this was still affecting 5-6 repos. I think the problem is that I'm set as the default reviewer on the bridge update PRs so the team does not have as much visibility into that.

**Comment by iwahbe** [comment]
I recommended that we remove the check, but I haven't actually looked into doing so.

A local workaround that we can apply as necessary is to remove the `CHANGELOG.md` file from the repo ([private link](https://github.com/pulumi/home/blob/930d86ebf50bb021bf9ddeedb7499b95fbb9e248/infrastructure/github-automation/changelog-bot/index.ts#L62-L82)).

CHANGELOG.md on pulumi-oci is blank and has never been edited after the initial commit.

**Comment by iwahbe** [comment]
@t0yv0 If you're aware of which 5-6 repos are still effected, I can create PRs similar to #270 to resolve the issue.

**Comment by t0yv0** [comment]
Ah excellent. Yes it's 

- https://github.com/pulumi/pulumi-onelogin/pull/158
- https://github.com/pulumi/pulumi-databricks/pull/253
- https://github.com/pulumi/pulumi-external/pull/62
- https://github.com/pulumi/pulumi-confluentcloud/pull/272
- https://github.com/pulumi/pulumi-archive/pull/58
- https://github.com/pulumi/pulumi-null/pull/41


This one fails license check?
https://github.com/pulumi/pulumi-tls/pull/324

**Comment by iwahbe** [comment]
I have removed the CHANGELOG.md from the providers you mentioned. I think the TLS PR that you mentioned is old (>2 weeks). Newer PRs are passing license check.
