### ISSUE TITLE
OCI Container Repo - immutable parameters is not valid 

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-oci#3]
### What happened?

When applying pulumi oci with the resource as oci. artefacts.ContainerRepository ,with value for parameter - is_immutable ,its failing 

```
 oci:Artifacts:ContainerRepository (testContainerRepository):
    error: 1 error occurred:
        * 400-BAD_REQUEST, Setting isImmutable is not currently supported

```

### Steps to reproduce

Follow the pulumi documentation with is_mutable parameter 

https://www.pulumi.com/registry/packages/oci/api-docs/artifacts/containerrepository/#inputs 

### Expected Behavior

This parameter should be removed from the documentation 

### Actual Behavior

The execution is failing 

### Versions used

(venv) rahulmr_in@rahulmr_in-mac pulumi_oci_devops % pulumi about
CLI          
Version      3.33.1
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME    VERSION
oci     0.1.1
python  unknown

Host     
OS       darwin
Version  11.6.3
Arch     x86_64

This project is written in python (/Users/rahulmr_in/Oracle Content - Accounts/Oracle Content/code/pulumi_oci_devops/venv/bin/python3 v3.8.9)

Current Stack: oci-devops-oke

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::pulumi:pulumi:Stack::pulumi-python-oci-devops-oke-oci-devops-oke
pulumi:providers:oci  urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::pulumi:providers:oci::default_0_1_1

Found no pending operations associated with oci-devops-oke

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/RahulMR42
User           RahulMR42
Organizations  RahulMR42

NAME        VERSION
pip         22.1.1
pulumi-oci  0.1.1
setuptools  62.3.2
wheel       0.37.1

Pulumi locates its logs in /var/folders/hn/2m651xss3vngsxk53znm1r680000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @RahulMR42 

This parameter is allowed to be set as the Terraform schema (from which we generate the Pulumi provider) is marking the parameter as `optional` - therefore it can be set

https://github.com/oracle/terraform-provider-oci/blob/master/internal/service/artifacts/artifacts_container_repository_resource.go#L42

Paul
