### ISSUE TITLE
`TF_VAR_compartment_ocid` env var is ignored

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-oci#607]
### Describe what happened

Hi,

I am using this provider with the following environment variables:

```
TF_VAR_auth=ApiKey
TF_VAR_user_ocid=""
TF_VAR_tenancy_ocid=""
TF_VAR_fingerprint=""
TF_VAR_private_key=""
TF_VAR_region=""

TF_VAR_compartment_ocid=""
```

The first group of env vars allows me to avoid to define an [oci.Provider](https://www.pulumi.com/registry/packages/oci/api-docs/provider/).

But I have to manually pass the `compartment_id` for each resource.

Reading [this](https://registry.terraform.io/providers/oracle/oci/latest/docs/guides/resource_discovery#exporting-resources-to-another-compartment), I would have expected that the provider would read that environment variable.

Any suggestions?

### Sample program

```python
import pulumi_oci as oci

oci.core.Vcn(
    "vcn",
    display_name="vcn",
    cidr_blocks=["10.0.0.0/24"],
    compartment_id=environ["TF_VAR_compartment_ocid"],
)
````

### Log output

```console
  pulumi:pulumi:Stack (oci-k3s-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/data/pulumi/__main__.py", line 7, in <module>
        vpc = Network(
            "main",
        ...<3 lines>...
            ),
        )
      File "/data/pulumi/network.py", line 32, in __init__
        oci.core.Vcn(
            "vcn",
        ...<3 lines>...
        )
      File "/usr/local/lib/python3.13/site-packages/pulumi_oci/core/vcn.py", line 806, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.13/site-packages/pulumi_oci/core/vcn.py", line 835, in _internal_init
        raise TypeError("Missing required property 'compartment_id'")
    TypeError: Missing required property 'compartment_id'
```

### Output of `pulumi about`

```
CLI          
Version      3.136.1
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  command     1.0.1
resource  oci         2.11.0
language  python      unknown

Host     
OS       debian
Version  12.7
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.13.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal

Dependencies:
NAME               VERSION
pip                24.2
pulumi_command     1.0.1
pulumi_oci         2.11.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@yellowhat Thanks for opening an issue. As far as I'm aware, [`TF_VAR_*`](https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_var_name) is a Terraform construct. I'm frankly surprised that it works for configuring the pulumi-oci provider at all.

If you want to set `compartment_id` on all resources that support the variable, I would look into [stack transforms](https://www.pulumi.com/docs/iac/concepts/options/transforms/#stack-transforms).
