### ISSUE TITLE
SecurityList related types are missing in Go

### ISSUE THREAD

**Issue by NominalTrajectory** [pulumi/pulumi-oci#64]
### What happened?

I am unable to add either `IngressSecurityRules` or `EngressSecurityRules` when creating a `SecurityList` using the Go SDK.
At least the following types are not defined:
- `SecurityListEgressSecurityRuleArray`
- `SecurityListEgressSecurityRuleArgs`
- `SecurityListIngressSecurityRuleArray`
- `SecurityListIngressSecurityRuleArgs`

### Steps to reproduce

Using
```sh
github.com/pulumi/pulumi-oci/sdk  0.5.0
github.com/pulumi/pulumi/sdk/v3   3.44.2
```

Create a compartment and VCN, then try to create a SecurityList

Create a new security list as follows
```go
name := "test-security-list"
_, err := core.NewSecurityList(ctx, name, &core.SecurityListArgs{
		CompartmentId: compartment.ID()
		VcnId:         vcn.ID(),
		DisplayName:   pulumi.String(name),
		EgressSecurityRules: core.SecurityListEgressSecurityRuleArray{
			core.SecurityListEgressSecurityRuleArgs{
				Protocol:    pulumi.String("all"),
				Destination: pulumi.String("0.0.0.0/0"),
			},
		},
})
```

### Expected Behavior

Should be able to use types 

- `SecurityListEgressSecurityRuleArray`
- `SecurityListEgressSecurityRuleArgs`
- `SecurityListIngressSecurityRuleArray`
- `SecurityListIngressSecurityRuleArgs`

### Actual Behavior

```sh
Unresolved type 'SecurityListEgressSecurityRuleArray'
```

### Output of `pulumi about`

```sh
CLI          
Version      3.50.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME  VERSION
go    unknown
oci   0.5.0

Host     
OS       darwin
Version  12.5
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.19.1 darwin/amd64'

Dependencies:
NAME                              VERSION
github.com/pulumi/pulumi-oci/sdk  0.5.0
github.com/pulumi/pulumi/sdk/v3   3.44.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @NominalTrajectory 

If I open https://github.com/pulumi/pulumi-oci/blob/main/sdk/go/oci/core/pulumiTypes.go, I can see the type around lines 16527

```
type SecurityListEgressSecurityRuleArray []SecurityListEgressSecurityRuleInput

func (SecurityListEgressSecurityRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SecurityListEgressSecurityRule)(nil)).Elem()
}

func (i SecurityListEgressSecurityRuleArray) ToSecurityListEgressSecurityRuleArrayOutput() SecurityListEgressSecurityRuleArrayOutput {
	return i.ToSecurityListEgressSecurityRuleArrayOutputWithContext(context.Background())
}

func (i SecurityListEgressSecurityRuleArray) ToSecurityListEgressSecurityRuleArrayOutputWithContext(ctx context.Context) SecurityListEgressSecurityRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityListEgressSecurityRuleArrayOutput)
}
```

Similarly, other types seem to be there too.

Do you maybe have a complete program that I could run to reproduce your error?

**Comment by NominalTrajectory** [comment]
Hi @mikhailshilkov, thanks for your response.

I think the issue was on my side. I created a new Go project and reinstalled pulumi and the OCI provider and now all types I could not used before are being properly resolved. Unfortunately, I was not able to understand what caused the problem but this issue can be closed.

**Comment by ericrudder** [comment]
Thanks for letting us know @NominalTrajectory
