### ISSUE TITLE
Can't create Db System, multiple types in dbSystem.go do not exist

### ISSUE THREAD

**Issue by josephhaddad55** [pulumi/pulumi-oci#93]
### What happened?

When attempting to create a new database system with `NewDbSystem` I'm unable to create a proper request body with `DbSystemArgs` because the following types don't exist in the `pulumi` go oci SDK:

- [`DbSystemDbHomeInput`](https://github.com/pulumi/pulumi-oci/blob/main/sdk/go/oci/database/dbSystem.go#L591)
- [`DbSystemDbSystemOptionsPtrInput`](https://github.com/pulumi/pulumi-oci/blob/main/sdk/go/oci/database/dbSystem.go#L593)
- [`DbSystemDataCollectionOptionsPtrInput `](https://github.com/pulumi/pulumi-oci/blob/main/sdk/go/oci/database/dbSystem.go#L583)
- [`DbSystemMaintenanceWindowDetailsPtrInput`](https://github.com/pulumi/pulumi-oci/blob/main/sdk/go/oci/database/dbSystem.go#L615)

### Steps to reproduce

Attempt to create a new database system using `database.NewDbSystem` with arguments `DataCollectionOptions`, `DbHome`, `DbSystemOptions`, `MaintenanceWindowDetails` and all the other required arguments.

### Expected Behavior

The `DbSystemArgs` input types should be available in the SDK. 

### Actual Behavior

They are not. 

### Output of `pulumi about`

```shell
CLI          
Version      3.56.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME  VERSION
go    unknown
oci   0.10.0

Dependencies:
NAME                              VERSION
github.com/pulumi/pulumi-oci/sdk  0.10.0
github.com/pulumi/pulumi/sdk/v3   3.56.0
```

**Comment by jazzyfresh** [comment]
Thank you for reporting!

This seems like it could be a bug in code generation. Could you please provide a minimal code sample that reproduces the issue, as well as the output logs from the Pulumi CLI with the exact error?

**Comment by josephhaddad55** [comment]
Hey @jazzyfresh, after working through this locally more, I found this isn't a bug. Thanks again.
